# Generated by Django 4.1 on 2022-11-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('dni', models.PositiveIntegerField()),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(blank=True, max_length=50, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('NE', 'No Especifica')], default='NE', max_length=10, null=True)),
                ('salario_mensual', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('departamento', models.CharField(blank=True, max_length=16, null=True)),
                ('foto_perfil', models.TextField(blank=True, null=True)),
                ('tipo_usuario', models.CharField(choices=[('ES', 'Empleado_Secretario'), ('EAI', 'Empleado_Agente Inmobiliario'), ('EM', 'Empleado_Marketing'), ('EJD', 'Empleado_Jefe de Departamento'), ('EC', 'Empleado_Cajero'), ('EAS', 'Empleado_Administrador de Sistema'), ('EGG', 'Empleado_Gerente General'), ('CP', 'Cliente_Particular'), ('CC', 'Cliente_Corporativo')], max_length=50)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
