# Generated by Django 3.2.12 on 2022-12-04 20:08

import applications.user.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'verbose_name': 'Ciudad', 'verbose_name_plural': 'Listado de Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name': 'Pais', 'verbose_name_plural': 'Listado de Paises'},
        ),
        migrations.AlterModelOptions(
            name='propiedad',
            options={'verbose_name': 'Propiedad', 'verbose_name_plural': 'Listado de Propiedades'},
        ),
        migrations.AlterModelOptions(
            name='propiedadrutadocumento',
            options={'verbose_name': 'Imagenes de Propiedades', 'verbose_name_plural': 'Imagenes de Propiedades'},
        ),
        migrations.AlterModelOptions(
            name='provincia',
            options={'verbose_name': 'Provincia', 'verbose_name_plural': 'Listado de Provincias'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Listado de Usuarios'},
        ),
        migrations.AlterField(
            model_name='cita',
            name='f_asignacion_cita',
            field=models.DateField(blank=True, db_column='F_Asignacion_Cita', null=True, verbose_name='Fecha de asignacion - Cita'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='f_cita',
            field=models.DateField(db_column='F_Cita', null=True, verbose_name='Fecha de Cita'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='f_concluye_cita',
            field=models.DateField(blank=True, db_column='F_Concluye_Cita', null=True, verbose_name='Fecha de finalizacion - Cita'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='f_creacion_cita',
            field=models.DateField(db_column='F_Creacion_Cita', verbose_name='Fecha de creacion - Cita'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='h_asignacion_cita',
            field=models.TimeField(blank=True, db_column='H_Asignacion_Cita', null=True, verbose_name='Hora de asignacion - Cita'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='h_cita',
            field=models.TimeField(db_column='H_Cita', null=True, verbose_name='Hora de Cita'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='h_concluye_cita',
            field=models.TimeField(blank=True, db_column='H_Concluye_Cita', null=True, verbose_name='Hota de finalizacion - Cita'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='h_creacion_cita',
            field=models.TimeField(db_column='H_Creacion_Cita', verbose_name='Hora de creacion - Cita'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='id_adquiere_o_alquila',
            field=models.ForeignKey(blank=True, db_column='ID_Adquiere_o_Alquila', limit_choices_to=models.Q(('tipo_usuario', 'CP'), ('tipo_usuario', 'CC'), _connector='OR'), null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Dueño/Inquilino'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='id_dueño',
            field=models.ForeignKey(db_column='ID_Dueño', limit_choices_to=models.Q(('tipo_usuario', 'CP'), ('tipo_usuario', 'CC'), _connector='OR'), on_delete=django.db.models.deletion.RESTRICT, related_name='dueño_propiedad', to=settings.AUTH_USER_MODEL, verbose_name='Dueño a cargo'),
        ),
        migrations.AlterField(
            model_name='propiedadrutadocumento',
            name='id_propiedad_documento',
            field=models.ForeignKey(db_column='ID_Propiedad_Documento', on_delete=django.db.models.deletion.CASCADE, to='user.propiedad', verbose_name='Propiedad'),
        ),
        migrations.AlterField(
            model_name='propiedadrutadocumento',
            name='ruta_pd',
            field=models.ImageField(db_column='Ruta_PD', upload_to=applications.user.models.PropiedadRutaDocumento.generateRutaPropiedad, verbose_name='Ruta de imagen'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(upload_to=applications.user.models.Usuario.generateRutaUsuarios),
        ),
    ]
