# Generated by Django 4.1 on 2022-12-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.UniqueConstraint(fields=('propiedad_involucrada', 'client_solicita_cita'), name='Propiedad_Cliente'),
        ),
        migrations.AddConstraint(
            model_name='propiedad',
            constraint=models.UniqueConstraint(fields=('direccion', 'id_ciudad_propiedad'), name='Unica_Direccion'),
        ),
    ]
