# Generated by Django 3.2.12 on 2022-11-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='departamento',
            field=models.CharField(blank=True, choices=[('COM', 'Comercializacion'), ('ADM', 'Administracion')], max_length=16, null=True),
        ),
    ]
