# Generated by Django 4.1 on 2022-12-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_cita_propiedad_cliente_propiedad_unica_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedadrutadocumento',
            name='ruta_pd',
            field=models.ImageField(db_column='Ruta_PD', upload_to='propiedad/'),
        ),
    ]
