# Generated by Django 4.1 on 2022-12-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_propiedadrutadocumento_ruta_pd'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cita',
            name='Propiedad_Cliente',
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.UniqueConstraint(fields=('f_cita', 'h_cita', 'ai_atiende_cita'), name='Agente_Horario'),
        ),
    ]
