# Generated by Django 4.1 on 2022-12-01 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_cita_f_creacion_cita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='ai_atiende_cita',
            field=models.ForeignKey(blank=True, db_column='AI_Atiende_Cita', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ai_cita', to=settings.AUTH_USER_MODEL, verbose_name='Agente inmobiliario asignado'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='client_solicita_cita',
            field=models.ForeignKey(db_column='Client_Solicita_Cita', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Cliente quien solicita'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='nro_cita',
            field=models.AutoField(db_column='NRO_Cita', primary_key=True, serialize=False, verbose_name='Cita N°'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='propiedad_involucrada',
            field=models.ForeignKey(db_column='Propiedad_Involucrada', on_delete=django.db.models.deletion.CASCADE, to='user.propiedad', verbose_name='Codigo propiedad'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='secre_asigna_cita',
            field=models.ForeignKey(blank=True, db_column='Secre_Asigna_Cita', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='secre_cita', to=settings.AUTH_USER_MODEL, verbose_name='Secretaria a cargo'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='tipo_cita',
            field=models.CharField(choices=[('SOL', 'Solicitud'), ('AG', 'Agendada')], db_column='Tipo_Cita', max_length=9, verbose_name='Cita de tipo'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='direccion',
            field=models.CharField(db_column='Direccion', max_length=100, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='estado_propiedad',
            field=models.CharField(choices=[('VEN', 'Venta'), ('ALQ', 'Alquiler')], db_column='Estado_Propiedad', max_length=8, verbose_name='Estado de la Propiedad'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='id_ciudad_propiedad',
            field=models.ForeignKey(db_column='ID_Ciudad_Propiedad', on_delete=django.db.models.deletion.RESTRICT, to='user.ciudad', verbose_name='Ciudad donde se encuentra'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='id_dueño',
            field=models.ForeignKey(db_column='ID_Dueño', on_delete=django.db.models.deletion.RESTRICT, related_name='dueño_propiedad', to=settings.AUTH_USER_MODEL, verbose_name='Dueño a cargo'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='id_propiedad',
            field=models.AutoField(db_column='ID_Propiedad', primary_key=True, serialize=False, verbose_name='Codigo Propiedad'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='metros_cuadrados',
            field=models.DecimalField(db_column='Metros_Cuadrados', decimal_places=0, max_digits=10, verbose_name='Metros Cuadrados'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='pisos',
            field=models.PositiveIntegerField(db_column='Pisos', verbose_name='Piso'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='precio_sugerido',
            field=models.DecimalField(db_column='Precio_Sugerido', decimal_places=0, max_digits=10, verbose_name='Precio sugerido'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='tipo_propiedad',
            field=models.CharField(choices=[('CAS', 'Casa'), ('DEP', 'Departamento'), ('GAL', 'Galpon'), ('CAMP', 'Campo'), ('TER', 'Terreno')], db_column='Tipo_Propiedad', max_length=12, verbose_name='Propiedad de tipo'),
        ),
    ]
