# Generated by Django 4.1 on 2022-12-01 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_cita_options_alter_ciudad_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='ai_atiende_cita',
            field=models.ForeignKey(blank=True, db_column='AI_Atiende_Cita', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ai_cita', to=settings.AUTH_USER_MODEL, verbose_name='Agente inmobiliario asignado'),
        ),
    ]
