# Generated by Django 4.1 on 2022-12-01 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_cita_ai_atiende_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='ai_atiende_cita',
            field=models.ForeignKey(blank=True, db_column='AI_Atiende_Cita', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ai_cita', to=settings.AUTH_USER_MODEL, verbose_name='Agente inmobiliario asignado'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='client_solicita_cita',
            field=models.ForeignKey(db_column='Client_Solicita_Cita', limit_choices_to={'tipo_usuario': 'CC'}, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Cliente quien solicita'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='f_cita',
            field=models.DateField(blank=True, db_column='F_Cita', null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='h_cita',
            field=models.TimeField(blank=True, db_column='H_Cita', null=True, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='propiedad_involucrada',
            field=models.ForeignKey(db_column='Propiedad_Involucrada', on_delete=django.db.models.deletion.CASCADE, to='user.propiedad', verbose_name='Codigo de propiedad'),
        ),
    ]
