# Generated by Django 4.1 on 2022-12-01 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_cita_ai_atiende_cita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='client_solicita_cita',
            field=models.ForeignKey(db_column='Client_Solicita_Cita', limit_choices_to={'tipo_usuario': 'CP'}, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Cliente quien solicita'),
        ),
    ]
