# Generated by Django 4.1 on 2022-12-02 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_cita_client_solicita_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='ai_atiende_cita',
            field=models.ForeignKey(blank=True, db_column='AI_Atiende_Cita', limit_choices_to={'tipo_usuario': 'AI'}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ai_cita', to=settings.AUTH_USER_MODEL, verbose_name='Agente inmobiliario asignado'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='client_solicita_cita',
            field=models.ForeignKey(db_column='Client_Solicita_Cita', limit_choices_to={'tipo_usuario': 'CC'}, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Cliente quien solicita'),
        ),
    ]
