# Generated by Django 4.1 on 2022-12-02 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_cita_ai_atiende_cita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='ai_atiende_cita',
            field=models.ForeignKey(blank=True, db_column='AI_Atiende_Cita', limit_choices_to={'tipo_usuario': 'EAI'}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ai_cita', to=settings.AUTH_USER_MODEL, verbose_name='Agente inmobiliario asignado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
