# Generated by Django 4.1 on 2022-12-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_cita_secre_asigna_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='f_cita',
            field=models.DateField(db_column='F_Cita', null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='h_cita',
            field=models.TimeField(db_column='H_Cita', null=True, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
